self: super:
let
  # mkGitTkn = namePrefix: jsonFile: { ... }@args: "";
in
{
  # tkn = super.tektoncd-cli;
  # tkn-git = mkGitTkn "tkn-git" ../repos/tkn-master.json { };
  # tkn-pac = …
  # tkn-pac-git = …
  # tkn-local = …
  # tkn-local-git = …
  # catlin = …
  # catlin-git = …
}
